export const All = [
  {
    id: 0,
    name: "앙시앙",
    url: `${process.env.PUBLIC_URL}/img/ancient.png`,
    ban: "광안리 신상 핫플",
    hash: "#페스츄리 크레페",
    add: "부산 수영구 광남로 77 1층",
    time: "11:30 ~ 20:00",
    break: "화요일 정기휴무",
    rec: "피스타치오 크레페, 발로나 페스츄리롤",
  },

  {
    id: 1,
    name: "프레제",
    url: `${process.env.PUBLIC_URL}/img/fraiser.png`,
    ban: "당일생산 비건빵",
    hash: "#노밀가루, 노계란",
    add: "부산 수영구 수영로 386 1층",
    time: "08:00 ~ 22:00",
    break: "연중무휴",
    rec: "밤식빵, 단호박 모닝빵",
  },

  {
    id: 2,
    name: "메트르아티정",
    url: `${process.env.PUBLIC_URL}/img/maitre.jpeg`,
    ban: "2024 블루리본 서베이",
    hash: "#프랑스빵",
    add: "부산 수영구 남천동로22번길 21",
    time: "09:00 ~ 20:00",
    break: "월요일 정기휴무",
    rec: "크로와상, 건강빵",
  },

  {
    id: 3,
    name: "서희와제과",
    url: `${process.env.PUBLIC_URL}/img/seo.png`,
    ban: "캐치테이블 2024 BEST",
    hash: "#통밀밤팥빵",
    add: "부산 수영구 광남로 89 1층",
    time: "11:00 ~ 19:00",
    break: "월요일,화요일 정기휴무",
    rec: "통밀밤팥빵, 고구마소보루",
  },

  {
    id: 4,
    name: "어메이징 베이커리",
    url: `${process.env.PUBLIC_URL}/img/amaizing.jpeg`,
    ban: "백화점 식품관 입점",
    hash: "#소금빵",
    add: "부산 수영구 광남로 87 1층",
    time: "10:30 ~ 20:00",
    break: "화요일 정기휴무",
    rec: "크림소금빵, 버터꾸덕바",
  },

  {
    id: 5,
    name: "이븐도우",
    url: `${process.env.PUBLIC_URL}/img/evendough.png`,
    ban: "광안리 신상 핫플",
    hash: "#치아바타",
    add: "부산 수영구 민락로 33번길 31 1층",
    time: "11:00 ~ 20:00",
    break: "월요일 정기휴무",
    rec: "밤폭탄치아바타, 통꿀구마치아바타",
  },

  {
    id: 6,
    name: "동양사라다",
    url: `${process.env.PUBLIC_URL}/img/dongyang.jpeg`,
    ban: "레트로무드의 베이커리",
    hash: "#사라다빵",
    add: "부산 수영구 남천서로 20번길 31",
    time: "11:00 ~ 16:00",
    break: "월요일 정기휴무",
    rec: "감자사라다빵, 옛날동양햄버거",
  },

  {
    id: 7,
    name: "더베이베이커리",
    url: `${process.env.PUBLIC_URL}/img/thebay.jpeg`,
    ban: "캐치테이블 2024 BEST",
    hash: "#맘모스빵",
    add: "부산 수영구 수영로 510번길 30 1층",
    time: "11:30 ~ 17:00",
    break: "화요일,수요일 정기휴무",
    rec: "모찌밤팥빵, 치아바타샌드위치",
  },
];
