export const All = [
  {
    id: 0,
    name: "앙시앙",
    // url: `${process.env.PUBLIC_URL}/img/ancien.png`,
    url: "https://search.pstatic.net/common/?src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20240816_70%2F1723780179092G3A9Y_JPEG%2FIMG_4779.JPG",

    ban: "광안리 신상 핫플",
    hash: "#페스츄리 크레페",
    add: "부산 수영구 광남로 77 1층",
    time: "11:30 ~ 20:00",
    break: "화요일 정기휴무",
    rec: "피스타치오 크레페, 발로나 페스츄리롤",
  },

  {
    id: 1,
    name: "프레제",
    url: `${process.env.PUBLIC_URL}/img/fraiser.png`,
    ban: "당일생산 비건빵",
    hash: "#노밀가루, 노계란",
    add: "부산 수영구 수영로 386 1층",
    time: "08:00 ~ 22:00",
    break: "연중무휴",
    rec: "밤식빵, 단호박 모닝빵",
  },

  {
    id: 2,
    name: "메트르아티정",
    url: `${process.env.PUBLIC_URL}/img/maitre.jpeg`,
    ban: "2024 블루리본 서베이",
    hash: "#프랑스빵",
    add: "부산 수영구 남천동로22번길 21",
    time: "09:00 ~ 20:00",
    break: "월요일 정기휴무",
    rec: "크로와상, 건강빵",
  },

  {
    id: 3,
    name: "서희와제과",
    url: `${process.env.PUBLIC_URL}/img/seo.png`,
    ban: "캐치테이블 2024 BEST",
    hash: "#통밀밤팥빵",
    add: "부산 수영구 광남로 89 1층",
    time: "11:00 ~ 19:00",
    break: "월요일,화요일 정기휴무",
    rec: "통밀밤팥빵, 고구마소보루",
  },

  {
    id: 4,
    name: "어메이징 베이커리",
    url: `${process.env.PUBLIC_URL}/img/amaizing.jpeg`,
    ban: "백화점 식품관 입점",
    hash: "#소금빵",
    add: "부산 수영구 광남로 87 1층",
    time: "10:30 ~ 20:00",
    break: "화요일 정기휴무",
    rec: "크림소금빵, 버터꾸덕바",
  },

  {
    id: 5,
    name: "이븐도우",
    url: `${process.env.PUBLIC_URL}/img/evendough.png`,
    ban: "광안리 신상 핫플",
    hash: "#치아바타",
    add: "부산 수영구 민락로 33번길 31 1층",
    time: "11:00 ~ 20:00",
    break: "월요일 정기휴무",
    rec: "밤폭탄치아바타, 통꿀구마치아바타",
  },

  {
    id: 6,
    name: "동양사라다",
    url: `${process.env.PUBLIC_URL}/img/dongyang.jpeg`,
    ban: "레트로무드의 베이커리",
    hash: "#사라다빵",
    add: "부산 수영구 남천서로 20번길 31",
    time: "11:00 ~ 16:00",
    break: "월요일 정기휴무",
    rec: "감자사라다빵, 옛날동양햄버거",
  },

  {
    id: 7,
    name: "더베이베이커리",
    url: `${process.env.PUBLIC_URL}/img/thebay.jpeg`,
    ban: "캐치테이블 2024 BEST",
    hash: "#맘모스빵",
    add: "부산 수영구 수영로 510번길 30 1층",
    time: "11:30 ~ 17:00",
    break: "화요일,수요일 정기휴무",
    rec: "모찌밤팥빵, 치아바타샌드위치",
  },

  {
    id: 8,
    name: "순쌀빵",
    url: `${process.env.PUBLIC_URL}/img/ssal.jpeg`,
    ban: "전제품 국내산 쌀사용",
    hash: "#쉬폰빵",
    add: "부산 수영구 광안해변로 122 삼익비치 B상가",
    time: "08:00 ~ 23:59",
    break: "연중무휴",
    rec: "쌀식빵, 쌀건강빵",
  },

  {
    id: 9,
    name: "소묘양과자점",
    url: `${process.env.PUBLIC_URL}/img/somyo.jpeg`,
    ban: "수제케이크 전문점",
    hash: "#생과일케이크",
    add: "부산 수영구 남천동로 10번길 10 106호",
    time: "11:30 ~ 20:00",
    break: "매주 일요일 휴무",
    rec: "소금빵, 밤치즈케이크",
  },

  {
    id: 10,
    name: "하우스멜",
    url: `${process.env.PUBLIC_URL}/img/hausmell.jpeg`,
    ban: "소금빵 맛집",
    hash: "#소금빵프렌치토스트",
    add: "부산 수영구 광안로 49번길 87 1층",
    time: "12:00 ~ 19:00",
    break: "매주 목요일 휴무",
    rec: "쪽파크림치즈소금빵",
  },

  {
    id: 11,
    name: "빅토리아베이커리",
    url: `${process.env.PUBLIC_URL}/img/vic.jpeg`,
    ban: "홀케이크 주문예약",
    hash: "#컵케이크",
    add: "부산 수영구 민락로 34번길 12-3 2층",
    time: "12:00 ~ 19:00",
    break: "매주 월요일 휴무",
    rec: "레몬 타르트, 빅토리아스펀지케이크",
  },

  {
    id: 12,
    name: "무슈뱅상",
    // url: `${process.env.PUBLIC_URL}/img/monsieur.png`,
    url: "https://search.pstatic.net/common/?src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200411_186%2F1586613677353mfDW1_JPEG%2FOLrCmL1EcdWyal52Tqp-4kDb.jpg",
    ban: "2024 블루리본 서베이",
    hash: "#천연발효종",
    add: "부산 수영구 광남로 48번길 19",
    time: "11:00 ~ 16:20",
    break: "매주 월요일,화요일 휴무",
    rec: "무화과르방, 바텅",
  },

  {
    id: 13,
    name: "비비비",
    url: `${process.env.PUBLIC_URL}/img/bbb.jpeg`,
    ban: "구움과자 전문점",
    hash: "#에그타르트",
    add: "부산 수영구 수영로 582번길 21 1층",
    time: "09:30 ~ 20:00",
    break: "매주 목요일 휴무",
    rec: "에그타르트, 옥수수타르트",
  },

  {
    id: 14,
    name: "올선데이",
    // url: `${process.env.PUBLIC_URL}/img/allsun.jpeg`,
    url: "https://search.pstatic.net/common/?src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20230503_176%2F16830926724522f8it_JPEG%2FKakaoTalk_20230502_194153674_02.jpg",
    ban: "유기농 밀가루 사용",
    hash: "#베이글",
    add: "부산 수영구 광안로 61번길 28 1층",
    time: "10:00 ~ 21:30",
    break: "연중무휴",
    rec: "감자치즈베이글, 올리브베이글",
  },

  {
    id: 15,
    name: "홍익당",
    url: `${process.env.PUBLIC_URL}/img/hong.jpeg`,
    ban: "유기농밀 베이커리",
    hash: "#통밀건강빵",
    add: "부산 수영구 광안해변로 326번길 31 이편한세상오션테라스4단지 상가 111호",
    time: "9:00 ~ 22:00",
    break: "연중무휴",
    rec: "모찌식빵, 모카모찌",
  },

  {
    name: "랜디스도넛",
    url: `${process.env.PUBLIC_URL}/img/randys.jpeg`,
    ban: "아이언맨이 좋아한 도넛",
    hash: "#시즌도넛",
    add: "부산 수영구 수영로 510번길 58",
    time: "11:00 ~ 21:00",
    break: "연중무휴",
    rec: "글레이즈도넛, 버터크림도넛",
  },
];
